import type { TournamentPlayer } from "../types";
import type { GolfDataProvider } from "./index";

export const mockLeaderboard: TournamentPlayer[] = [
  {
    id: "scottie-scheffler",
    name: "Scottie Scheffler",
    totalStrokes: 268,
    relativeToPar: -20,
    madeCut: true,
    status: "active",
    position: 1,
  },
  {
    id: "ludvig-aberg",
    name: "Ludvig Åberg",
    totalStrokes: 271,
    relativeToPar: -17,
    madeCut: true,
    status: "active",
    position: 2,
  },
  {
    id: "collin-morikawa",
    name: "Collin Morikawa",
    totalStrokes: 273,
    relativeToPar: -15,
    madeCut: true,
    status: "active",
    position: 3,
  },
  {
    id: "bryson-dechambeau",
    name: "Bryson DeChambeau",
    totalStrokes: 274,
    relativeToPar: -14,
    madeCut: true,
    status: "active",
    position: 4,
  },
  {
    id: "rory-mcilroy",
    name: "Rory McIlroy",
    totalStrokes: 275,
    relativeToPar: -13,
    madeCut: true,
    status: "active",
    position: 5,
  },
  {
    id: "xander-schauffele",
    name: "Xander Schauffele",
    totalStrokes: 275,
    relativeToPar: -13,
    madeCut: true,
    status: "active",
    position: 5,
  },
  {
    id: "jon-rahm",
    name: "Jon Rahm",
    totalStrokes: 276,
    relativeToPar: -12,
    madeCut: true,
    status: "active",
    position: 7,
  },
  {
    id: "tommy-fleetwood",
    name: "Tommy Fleetwood",
    totalStrokes: 277,
    relativeToPar: -11,
    madeCut: true,
    status: "active",
    position: 8,
  },
  {
    id: "hideki-matsuyama",
    name: "Hideki Matsuyama",
    totalStrokes: 277,
    relativeToPar: -11,
    madeCut: true,
    status: "active",
    position: 8,
  },
  {
    id: "brooks-koepka",
    name: "Brooks Koepka",
    totalStrokes: 278,
    relativeToPar: -10,
    madeCut: true,
    status: "active",
    position: 10,
  },
  {
    id: "min-woo-lee",
    name: "Min Woo Lee",
    totalStrokes: 278,
    relativeToPar: -10,
    madeCut: true,
    status: "active",
    position: 10,
  },
  {
    id: "shane-lowry",
    name: "Shane Lowry",
    totalStrokes: 279,
    relativeToPar: -9,
    madeCut: true,
    status: "active",
    position: 12,
  },
  {
    id: "cameron-young",
    name: "Cameron Young",
    totalStrokes: 279,
    relativeToPar: -9,
    madeCut: true,
    status: "active",
    position: 12,
  },
  {
    id: "jordan-spieth",
    name: "Jordan Spieth",
    totalStrokes: 280,
    relativeToPar: -8,
    madeCut: true,
    status: "active",
    position: 14,
  },
  {
    id: "justin-thomas",
    name: "Justin Thomas",
    totalStrokes: 280,
    relativeToPar: -8,
    madeCut: true,
    status: "active",
    position: 14,
  },
  {
    id: "corey-conners",
    name: "Corey Conners",
    totalStrokes: 281,
    relativeToPar: -7,
    madeCut: true,
    status: "active",
    position: 16,
  },
  {
    id: "patrick-cantlay",
    name: "Patrick Cantlay",
    totalStrokes: 281,
    relativeToPar: -7,
    madeCut: true,
    status: "active",
    position: 16,
  },
  {
    id: "jason-day",
    name: "Jason Day",
    totalStrokes: 282,
    relativeToPar: -6,
    madeCut: true,
    status: "active",
    position: 18,
  },
  {
    id: "adam-scott",
    name: "Adam Scott",
    totalStrokes: 282,
    relativeToPar: -6,
    madeCut: true,
    status: "active",
    position: 18,
  },
  {
    id: "akshay-bhatia",
    name: "Akshay Bhatia",
    totalStrokes: 283,
    relativeToPar: -5,
    madeCut: true,
    status: "active",
    position: 20,
  },
  {
    id: "tyrrell-hatton",
    name: "Tyrrell Hatton",
    totalStrokes: 283,
    relativeToPar: -5,
    madeCut: true,
    status: "active",
    position: 20,
  },
  {
    id: "cameron-smith",
    name: "Cameron Smith",
    totalStrokes: 284,
    relativeToPar: -4,
    madeCut: true,
    status: "active",
    position: 22,
  },
  {
    id: "viktor-hovland",
    name: "Viktor Hovland",
    totalStrokes: 284,
    relativeToPar: -4,
    madeCut: true,
    status: "active",
    position: 22,
  },
  {
    id: "will-zalatoris",
    name: "Will Zalatoris",
    totalStrokes: 285,
    relativeToPar: -3,
    madeCut: true,
    status: "active",
    position: 24,
  },
  {
    id: "sungjae-im",
    name: "Sungjae Im",
    totalStrokes: 285,
    relativeToPar: -3,
    madeCut: true,
    status: "active",
    position: 24,
  },
  {
    id: "nicolai-hojgaard",
    name: "Nicolai Højgaard",
    totalStrokes: 286,
    relativeToPar: -2,
    madeCut: true,
    status: "active",
    position: 26,
  },
  {
    id: "jake-knapp",
    name: "Jake Knapp",
    totalStrokes: 287,
    relativeToPar: -1,
    madeCut: true,
    status: "active",
    position: 27,
  },
  {
    id: "justin-rose",
    name: "Justin Rose",
    totalStrokes: 149,
    relativeToPar: 5,
    madeCut: false,
    status: "cut",
    position: null,
  },
  {
    id: "chris-gotterup",
    name: "Chris Gotterup",
    totalStrokes: 151,
    relativeToPar: 7,
    madeCut: false,
    status: "cut",
    position: null,
  },
  {
    id: "nico-echavarria",
    name: "Nico Echavarría",
    totalStrokes: 152,
    relativeToPar: 8,
    madeCut: false,
    status: "cut",
    position: null,
  },
  {
    id: "ben-griffin",
    name: "Ben Griffin",
    totalStrokes: 72,
    relativeToPar: 0,
    madeCut: false,
    status: "wd",
    position: null,
  },
];

export const mockProvider: GolfDataProvider = {
  getLeaderboard(): Promise<TournamentPlayer[]> {
    return Promise.resolve(mockLeaderboard);
  },
};